server:
  port: 8402

spring:
  application:
    name: hystrix-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

service-url:
  user-service: http://user-service

management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream' #暴露hystrix监控端点


#实例配置只需要将全局配置中的default换成与之对应的key即可。
#HystrixComandKey对应@HystrixCommand中的commandKey属性；
#HystrixCollapserKey对应@HystrixCollapser注解中的collapserKey属性；
#HystrixThreadPoolKey对应@HystrixCommand中的threadPoolKey属性。

#hystrix:
#  command:
#    HystrixComandKey: #将default换成HystrixComrnandKey
#      execution:
#        isolation:
#          strategy: THREAD
#  collapser:
#    HystrixCollapserKey: #将default换成HystrixCollapserKey
#      maxRequestsInBatch: 100
#  threadpool:
#    HystrixThreadPoolKey: #将default换成HystrixThreadPoolKey
#      coreSize: 10


#全局配置
#hystrix:
#  command: #用于控制HystrixCommand的行为
#    default:
#      execution:
#        isolation:
#          strategy: THREAD #控制HystrixCommand的隔离策略，THREAD->线程池隔离策略(默认)，SEMAPHORE->信号量隔离策略
#          thread:
#            timeoutInMilliseconds: 1000 #配置HystrixCommand执行的超时时间，执行超过该时间会进行服务降级处理
#            interruptOnTimeout: true #配置HystrixCommand执行超时的时候是否要中断
#            interruptOnCancel: true #配置HystrixCommand执行被取消的时候是否要中断
#          timeout:
#            enabled: true #配置HystrixCommand的执行是否启用超时时间
#          semaphore:
#            maxConcurrentRequests: 10 #当使用信号量隔离策略时，用来控制并发量的大小，超过该并发量的请求会被拒绝
#      fallback:
#        enabled: true #用于控制是否启用服务降级
#      circuitBreaker: #用于控制HystrixCircuitBreaker的行为
#        enabled: true #用于控制断路器是否跟踪健康状况以及熔断请求
#        requestVolumeThreshold: 20 #超过该请求数的请求会被拒绝
#        forceOpen: false #强制打开断路器，拒绝所有请求
#        forceClosed: false #强制关闭断路器，接收所有请求
#      requestCache:
#        enabled: true #用于控制是否开启请求缓存
#  collapser: #用于控制HystrixCollapser的执行行为
#    default:
#      maxRequestsInBatch: 100 #控制一次合并请求合并的最大请求数
#      timerDelayinMilliseconds: 10 #控制多少毫秒内的请求会被合并成一个
#      requestCache:
#        enabled: true #控制合并请求是否开启缓存
#  threadpool: #用于控制HystrixCommand执行所在线程池的行为
#    default:
#      coreSize: 10 #线程池的核心线程数
#      maximumSize: 10 #线程池的最大线程数，超过该线程数的请求会被拒绝
#      maxQueueSize: -1 #用于设置线程池的最大队列大小，-1采用SynchronousQueue，其他正数采用LinkedBlockingQueue
#      queueSizeRejectionThreshold: 5 #用于设置线程池队列的拒绝阀值，由于LinkedBlockingQueue不能动态改版大小，使用时需要用该参数来控制线程数
